import type { AppState, Cabinet, Specimen, SwapRequest } from "./types";

// 柜位编号：区-架-格，如 A-12-03
function cabinet(ids: string[]): Cabinet[] {
  return ids.map((id) => {
    const [zone, shelf] = id.split("-");
    return { id, zone, shelf: `${zone}-${shelf}架` };
  });
}

export const CABINETS: Cabinet[] = cabinet([
  "A-12-03",
  "A-12-04",
  "A-12-05",
  "A-13-01",
  "A-13-02",
  "B-08-01",
  "B-08-02",
  "B-08-03",
  "B-08-04",
  "B-12-04",
  "B-12-05",
  "C-03-02",
]);

const day = (offset: number) => new Date(Date.now() - offset * 86400000).toISOString();

export const SPECIMENS: Specimen[] = [
  {
    id: "sp-1",
    collectionNo: "HX-240615-01",
    species: "阔叶槭",
    family: "槭树科",
    location: "天目山·五里坡",
    elevation: 1420,
    habitat: "落叶阔叶林下，溪谷旁",
    collectors: "陈默、林晚",
    pressStatus: "已入库",
    identifyStatus: "已接受",
    cabinetId: "A-12-03",
    onLoan: false,
    receivedAt: day(40),
    moves: [{ at: day(33), type: "上柜", from: null, to: "A-12-03" }],
  },
  {
    id: "sp-2",
    collectionNo: "HX-240616-03",
    species: "黄山菊",
    family: "菊科",
    location: "清凉峰·大凸",
    elevation: 1680,
    habitat: "山顶灌丛草甸",
    collectors: "林晚、周禾",
    pressStatus: "已入库",
    identifyStatus: "已接受",
    cabinetId: "A-12-04",
    onLoan: false,
    receivedAt: day(38),
    moves: [{ at: day(30), type: "上柜", from: null, to: "A-12-04" }],
  },
  {
    id: "sp-3",
    collectionNo: "HX-240621-07",
    species: "天目琼花",
    family: "五福花科",
    location: "天目山·三里亭",
    elevation: 960,
    habitat: "林缘湿润处",
    collectors: "陈默",
    pressStatus: "已入库",
    identifyStatus: "已接受",
    cabinetId: "B-08-01",
    onLoan: true,
    loanNote: "市植物园科普展 2026-09",
    receivedAt: day(31),
    moves: [{ at: day(25), type: "上柜", from: null, to: "B-08-01" }],
  },
  {
    id: "sp-4",
    collectionNo: "HX-240702-12",
    species: "鳞毛蕨待定",
    family: "鳞毛蕨科",
    location: "清凉峰·阴湿沟谷",
    elevation: 1180,
    habitat: "常绿阔叶林下沟谷石缝",
    collectors: "周禾",
    pressStatus: "已入库",
    identifyStatus: "存疑",
    cabinetId: "B-08-02",
    onLoan: false,
    receivedAt: day(20),
    moves: [{ at: day(16), type: "上柜", from: null, to: "B-08-02" }],
  },
  {
    id: "sp-5",
    collectionNo: "HX-240710-05",
    species: "紫花前胡",
    family: "伞形科",
    location: "龙王山·千亩田",
    elevation: 1350,
    habitat: "沼泽化草甸边缘",
    collectors: "陈默、周禾",
    pressStatus: "已入库",
    identifyStatus: "已接受",
    cabinetId: "B-08-04",
    onLoan: false,
    receivedAt: day(14),
    moves: [{ at: day(10), type: "上柜", from: null, to: "B-08-04" }],
  },
  {
    id: "sp-6",
    collectionNo: "HX-240718-09",
    species: "中国绣球",
    family: "绣球花科",
    location: "天目山·开山老店",
    elevation: 1100,
    habitat: "山坡灌丛",
    collectors: "林晚",
    pressStatus: "已入库",
    identifyStatus: "已接受",
    cabinetId: "B-12-04",
    onLoan: false,
    receivedAt: day(9),
    moves: [
      { at: day(8), type: "上柜", from: null, to: "A-13-01" },
      { at: day(6), type: "对调", from: "A-13-01", to: "B-12-04", swapId: "SW-20260916-001" },
    ],
  },
  {
    id: "sp-7",
    collectionNo: "HX-240720-02",
    species: "山牛蒡",
    family: "菊科",
    location: "龙王山·千亩田",
    elevation: 1480,
    habitat: "疏林荒地",
    collectors: "周禾、林晚",
    pressStatus: "已入库",
    identifyStatus: "已接受",
    cabinetId: "A-13-02",
    onLoan: false,
    receivedAt: day(8),
    moves: [
      { at: day(7), type: "上柜", from: null, to: "B-12-05" },
      { at: day(6), type: "对调", from: "B-12-05", to: "A-13-02", swapId: "SW-20260916-001" },
    ],
  },
  // 未上柜：入库队列
  {
    id: "sp-8",
    collectionNo: "HX-240901-01",
    species: "槭属待定",
    family: "槭树科",
    location: "天目山·五里坡",
    elevation: 1390,
    habitat: "混交林下",
    collectors: "陈默",
    pressStatus: "已压制",
    identifyStatus: "待鉴定",
    cabinetId: null,
    onLoan: false,
    receivedAt: day(4),
    moves: [],
  },
  {
    id: "sp-9",
    collectionNo: "HX-240910-06",
    species: "蕨类待定",
    family: "未分科",
    location: "清凉峰·阴湿沟谷",
    elevation: 1050,
    habitat: "沟谷石缝，腐殖质丰富",
    collectors: "周禾",
    pressStatus: "待压制",
    identifyStatus: "待鉴定",
    cabinetId: null,
    onLoan: false,
    receivedAt: day(2),
    moves: [],
  },
  {
    id: "sp-10",
    collectionNo: "HX-240918-03",
    species: "蓟属待定",
    family: "菊科",
    location: "龙王山·千亩田",
    elevation: 1500,
    habitat: "草甸向阳处",
    collectors: "林晚",
    pressStatus: "已压制",
    identifyStatus: "待鉴定",
    cabinetId: null,
    onLoan: false,
    receivedAt: day(1),
    moves: [],
  },
];

const historySwap: SwapRequest = {
  id: "SW-20260916-001",
  specimenAId: "sp-6",
  specimenBId: "sp-7",
  targetCabinetA: "B-12-04",
  targetCabinetB: "A-13-02",
  voucher: "柜位调整单 GD-20260916-07（馆务会批准）",
  note: "菊科标本按产区归架",
  status: "effective",
  createdAt: day(6),
  decidedAt: day(6),
  check: { pass: true, violations: [], checkedAt: day(6) },
};

export function createInitialState(): AppState {
  return {
    specimens: SPECIMENS,
    cabinets: CABINETS,
    swaps: [historySwap],
    seq: 2,
  };
}
